FROM python:3.9-slim AS builder

WORKDIR /build

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc \
        g++ \
        make \
        curl \
        git \
    && rm -rf /var/lib/apt/lists/*

COPY app.py .

RUN mkdir /build/artifact && \
    cp app.py /build/artifact/


FROM python:3.9-slim

WORKDIR /app

COPY --from=builder /build/artifact/app.py .

CMD ["python", "app.py"]