apiVersion: v1
kind: Pod

metadata:
  name: lab49-pod

spec:
  containers:
    - name: app
      image: python:3.9-slim

      command:
        - python
        - -c
        - |
          import os
          print("Password received:", os.getenv("DB_PASSWORD"))

      env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lab49-secret
              key: DB_PASSWORD
