FROM python:3.9-slim

WORKDIR /app

COPY /app/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY /app/ .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]

HEALTHCHECK --interval=5s --timeout=3s --retries=3 CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8001/does-not-exist')"
