apiVersion: v1
kind: Service
metadata:
  name: cloud-native-test-platform
spec:
  selector:
    app: cloud-native-test-platform

  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

  type: ClusterIP
